pages:
  stage: deploy
  script:
    - mkdir public
    - cp index.html public/index.html
    - cp apple-touch-icon.png public/apple-touch-icon.png
  artifacts:
    paths:
      - public
  only:
    - main
